# Generated by Django 4.2.2 on 2024-08-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
