# Generated by Django 4.2.2 on 2024-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
